### ISSUE TITLE
训练自己的数据集

### ISSUE THREAD

**Issue by varrella** [bubbliiiing/yolov4-tiny-pytorch#54]
大佬你好，想问下训练自己的数据集生成了权重之后，为什么在运行predict.py的时候出现了这个问题：
Traceback (most recent call last):
  File "C:/Users/11951/Desktop/bubbliiiing/yolov4-tiny/predict.py", line 14, in <module>
    yolo = YOLO()
  File "C:\Users\11951\Desktop\bubbliiiing\yolov4-tiny\yolo.py", line 99, in __init__
    self.generate()
  File "C:\Users\11951\Desktop\bubbliiiing\yolov4-tiny\yolo.py", line 110, in generate
    self.net.load_state_dict(torch.load(self.model_path, map_location=device))
  File "D:\Anaconda3\envs\milli\lib\site-packages\torch\nn\modules\module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for YoloBody:
	Unexpected key(s) in state_dict: "feat1_att.channelattention.fc1.weight", "feat1_att.channelattention.fc2.weight", "feat1_att.spatialattention.conv1.weight", "feat2_att.channelattention.fc1.weight", "feat2_att.channelattention.fc2.weight", "feat2_att.spatialattention.conv1.weight", "upsample_att.channelattention.fc1.weight", "upsample_att.channelattention.fc2.weight", "upsample_att.spatialattention.conv1.weight". 

训练过程：
---修改了train.py中:
 classes_path    = 'model_data/nuscenes_classes.txt'
model_path      = 'model_data/yolov4_tiny_weights_voc.pth'

---修改了voc_annotation.py：
classes_path     = 'model_data/nuscenes_classes.txt'

预测过程：
---修改了yolo.py：
"model_path": 'model_data/ep100-loss0.005-val_loss0.005.pth',
"classes_path": 'model_data/nuscenes_classes.txt',

然后就出现了上面的问题，大佬能不能帮忙看下哪一步出现了问题？

**Comment by bubbliiiing** [comment]
你当时phi没改对吧？

**Comment by varrella** [comment]
> 你当时phi没改对吧？

对的，我今天发现这个问题了，然而又有了新的问题。。。
我训练之后的权重检测不出目标是咋回事呀，训练了100个epoch，是这个训练权重出问题了嘛

训练过程：
---修改了train.py中:
classes_path = 'model_data/nuscenes_classes.txt'
model_path = 'model_data/yolov4_tiny_weights_voc_CBAM.pth'
phi = 2

---修改了voc_annotation.py：
classes_path = 'model_data/nuscenes_classes.txt'

预测过程：
---修改了yolo.py：
"model_path": 'model_data/ep100-loss0.004-val_loss0.004.pth',
"classes_path": 'model_data/nuscenes_classes.txt',
"phi": 2

**Comment by PJPomPom** [comment]
> 你当时phi没改对吧？
大佬我改phi=1用senet了，其他的也改了，训练完了，getmap也出现了类似问题，恳请赐教
![image](https://user-images.githubusercontent.com/77728649/150133352-7748d4b2-1bbb-457f-addb-970635f297dd.png)

**Comment by bubbliiiing** [comment]
训练和预测总有一个没改的
