### ISSUE TITLE
在加入注意力机制后，训练出现问题

### ISSUE THREAD

**Issue by Rywaii99** [bubbliiiing/yolov4-tiny-pytorch#71]
泡泡哥您好，我在改变phi的值并选择SE模块后，把预训练模型改成对应的yolov4_tiny_weights_voc_SE.pth，但是在训练时报了如下错误：
Traceback (most recent call last):
  File "D:/Code/train.py", line 162, in <module>
    pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) == np.shape(v)}
  File "D:/Code/train.py", line 162, in <dictcomp>
    pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) == np.shape(v)}
KeyError: 'feat1_att.fc.0.weight'

请问为什么使用添加了注意力机制的预训练模型会出现找不到权重的问题呀？我最开始训练添加注意力机制的网络时都是用的yolov4_tiny_weights_voc.pth，那个时候并没有报错。

**Comment by bubbliiiing** [comment]
phi你等于多少啊，什么时候的代码

**Comment by Rywaii99** [comment]
phi不为0的情况下都试了，分别使用对应的SE、CBAM和ECA的初始权重都会在初始化这报错。
使用的是您这次大更新之前的代码。

**Comment by Rywaii99** [comment]
我这次使用了yolov4_tiny_weights_voc.pth在phi=1时进行训练，然后根目录下get_map.py调用的yolo.py中的phi我也改成1了，但是在使用训练完的权重调用get_map.py测试时，依旧在权重赋值这里发生了错误，感觉注意力机制这几层的权重没有保存，或者对应的key不对。报错如下：
RuntimeError: Error(s) in loading state_dict for YoloBody:
	Missing key(s) in state_dict: "feat1_att.fc.0.weight", "feat1_att.fc.2.weight", "feat2_att.fc.0.weight", "feat2_att.fc.2.weight", "upsample_att.fc.0.weight", "upsample_att.fc.2.weight".

**Comment by SnakeHit** [comment]
遇到了同样的问题

**Comment by Rywaii99** [comment]
model path都改了，训练时保存还是按照一个epoch保存一次的策略，但是就是无法在phi不为0时加载带有注意力机制的权重，不论是我设定phi不为0训练后得到的权重还是百度网盘里提供的带有注意力机制的权重。加载时都是显示找不到对应层权重的key...

**Comment by bubbliiiing** [comment]
…我看了一遍。确实train.py和yolo.py的phi都没有问题，你截个图

**Comment by SnakeHit** [comment]
这是报错日志
```
(myconda) root@66bd78e8c494:/mnt/yolov4-tiny-pytorch# python predict.py img/street.jpg 
Traceback (most recent call last):
  File "predict.py", line 14, in <module>
    yolo = YOLO()
  File "/mnt/yolov4-tiny-pytorch/yolo.py", line 97, in __init__
    self.generate()
  File "/mnt/yolov4-tiny-pytorch/yolo.py", line 108, in generate
    self.net.load_state_dict(torch.load(self.model_path, map_location=device))
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for YoloBody:
        Missing key(s) in state_dict: "feat1_att.fc.0.weight", "feat1_att.fc.2.weight", "feat2_att.fc.0.weight", "feat2_att.fc.2.weight", "upsample_att.fc.0.weight", "upsample_att.fc.2.weight". 
        Unexpected key(s) in state_dict: "feat1_att.conv.weight", "feat2_att.conv.weight", "upsample_att.conv.weight".
```

**Comment by Ice-wave** [comment]
确实加了attention以后权值的key找不到
